# Generated by Django 5.1.7 on 2026-06-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='category',
            field=models.CharField(choices=[('Array', 'Array'), ('String', 'String'), ('Tree', 'Tree'), ('Graph', 'Graph'), ('DP', 'Dynamic Programming')], default='Array', max_length=50),
        ),
    ]
