# Generated by Django 5.1.7 on 2026-06-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_codingproblem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingproblem',
            name='category',
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='expected_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='test_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
