# Generated by Django 5.1.7 on 2026-06-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_remove_codingproblem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='test_cases',
            field=models.TextField(blank=True, help_text='\n        Format:\n        input|output\n\n        Example:\n\n        2\n        7|9\n\n        10\n        5|15\n        ', null=True),
        ),
    ]
