# Generated by Django 5.1.7 on 2026-06-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_codingproblem_test_cases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingproblem',
            name='test_cases',
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
