# Generated by Django 5.1.7 on 2026-06-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_remove_codingproblem_test_cases_codingproblem_hint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codingproblem',
            old_name='hint',
            new_name='hint_1',
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='hint_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='hint_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
