# Generated by Django 5.1.7 on 2026-06-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_rename_hint_codingproblem_hint_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingproblem',
            name='expected_output',
        ),
        migrations.RemoveField(
            model_name='codingproblem',
            name='test_input',
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='test_cases',
            field=models.TextField(blank=True, help_text='\nFormat:\n\ninput|output\n\nExample:\n\nhello|olleh\npython|nohtyp\ncoding|gnidoc\n', null=True),
        ),
    ]
