# Generated by Django 5.1.7 on 2026-06-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='memory',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='runtime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
