# Generated by Django 5.1.7 on 2026-06-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_memory_submission_runtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
