# Generated by Django 5.1.7 on 2026-06-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(default='python', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='runtime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
